# app.yaml

runtime: python312
env: standard
entrypoint: gunicorn -b :$PORT fedkovych.wsgi:application

handlers:
- url: /static
  static_dir: staticfiles/
- url: /.*
  script: auto

runtime_config:
  python_version: 3