# Generated by Django 5.1 on 2024-08-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Song",
        ),
        migrations.AlterField(
            model_name="video",
            name="mp4_file",
            field=models.FileField(
                upload_to="D:\\Lessons\\Fedkovych\\Fedkovych\\music-bot/music/"
            ),
        ),
    ]
