# Generated by Django 5.1 on 2024-08-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0002_delete_song_alter_video_mp4_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration_seconds",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="is_converted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="video",
            name="mp4_file",
            field=models.FileField(upload_to="music/"),
        ),
    ]
