# Generated by Django 5.1 on 2024-08-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0003_video_duration_seconds_video_is_converted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
